// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAppConfig(arg1) {
  return window['go']['main']['App']['DeleteAppConfig'](arg1);
}

export function GetFullConfig() {
  return window['go']['main']['App']['GetFullConfig']();
}

export function SelectCommandPath(arg1) {
  return window['go']['main']['App']['SelectCommandPath'](arg1);
}

export function UpdateAppConfig(arg1, arg2) {
  return window['go']['main']['App']['UpdateAppConfig'](arg1, arg2);
}
