// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteAppConfig(arg1:string):Promise<void>;

export function GetFullConfig():Promise<Record<string, main.AppConfig>>;

export function UpdateAppConfig(arg1:string,arg2:main.AppConfig):Promise<void>;
